DROP TABLE IF EXISTS usuario;
USE plantapp;
CREATE TABLE If NOT EXISTS usuario (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    correo VARCHAR(100) NOT NULL UNIQUE,
    contrasena VARCHAR(255) NOT NULL
);

SHOW TABLES;
DESCRIBE usuario;

